package com.ellis.goods.dal.db;

import com.ellis.goods.dal.db.GoodsInfoPo;
import com.ellis.goods.dal.db.GoodsInfoPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsInfoPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbggenerated Wed Nov 30 00:52:58 CST 2016
     */
    int countByExample(GoodsInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbggenerated Wed Nov 30 00:52:58 CST 2016
     */
    int deleteByExample(GoodsInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbggenerated Wed Nov 30 00:52:58 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbggenerated Wed Nov 30 00:52:58 CST 2016
     */
    int insert(GoodsInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbggenerated Wed Nov 30 00:52:58 CST 2016
     */
    int insertSelective(GoodsInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbggenerated Wed Nov 30 00:52:58 CST 2016
     */
    List<GoodsInfoPo> selectByExample(GoodsInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbggenerated Wed Nov 30 00:52:58 CST 2016
     */
    GoodsInfoPo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbggenerated Wed Nov 30 00:52:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") GoodsInfoPo record, @Param("example") GoodsInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbggenerated Wed Nov 30 00:52:58 CST 2016
     */
    int updateByExample(@Param("record") GoodsInfoPo record, @Param("example") GoodsInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbggenerated Wed Nov 30 00:52:58 CST 2016
     */
    int updateByPrimaryKeySelective(GoodsInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbggenerated Wed Nov 30 00:52:58 CST 2016
     */
    int updateByPrimaryKey(GoodsInfoPo record);
}