package com.ellis.order.dal.db;

import com.ellis.order.dal.db.OrderInfoPo;
import com.ellis.order.dal.db.OrderInfoPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderInfoPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Fri Dec 02 16:30:45 CST 2016
     */
    int countByExample(OrderInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Fri Dec 02 16:30:45 CST 2016
     */
    int deleteByExample(OrderInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Fri Dec 02 16:30:45 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Fri Dec 02 16:30:45 CST 2016
     */
    int insert(OrderInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Fri Dec 02 16:30:45 CST 2016
     */
    int insertSelective(OrderInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Fri Dec 02 16:30:45 CST 2016
     */
    List<OrderInfoPo> selectByExample(OrderInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Fri Dec 02 16:30:45 CST 2016
     */
    OrderInfoPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Fri Dec 02 16:30:45 CST 2016
     */
    int updateByExampleSelective(@Param("record") OrderInfoPo record, @Param("example") OrderInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Fri Dec 02 16:30:45 CST 2016
     */
    int updateByExample(@Param("record") OrderInfoPo record, @Param("example") OrderInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Fri Dec 02 16:30:45 CST 2016
     */
    int updateByPrimaryKeySelective(OrderInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Fri Dec 02 16:30:45 CST 2016
     */
    int updateByPrimaryKey(OrderInfoPo record);
}