package com.ellis.pay.dal.db;

import com.ellis.pay.dal.db.IphonePayLogPo;
import com.ellis.pay.dal.db.IphonePayLogPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IphonePayLogPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iphone_pay_log
     *
     * @mbggenerated Thu Dec 01 11:45:12 CST 2016
     */
    int countByExample(IphonePayLogPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iphone_pay_log
     *
     * @mbggenerated Thu Dec 01 11:45:12 CST 2016
     */
    int deleteByExample(IphonePayLogPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iphone_pay_log
     *
     * @mbggenerated Thu Dec 01 11:45:12 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iphone_pay_log
     *
     * @mbggenerated Thu Dec 01 11:45:12 CST 2016
     */
    int insert(IphonePayLogPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iphone_pay_log
     *
     * @mbggenerated Thu Dec 01 11:45:12 CST 2016
     */
    int insertSelective(IphonePayLogPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iphone_pay_log
     *
     * @mbggenerated Thu Dec 01 11:45:12 CST 2016
     */
    List<IphonePayLogPo> selectByExample(IphonePayLogPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iphone_pay_log
     *
     * @mbggenerated Thu Dec 01 11:45:12 CST 2016
     */
    IphonePayLogPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iphone_pay_log
     *
     * @mbggenerated Thu Dec 01 11:45:12 CST 2016
     */
    int updateByExampleSelective(@Param("record") IphonePayLogPo record, @Param("example") IphonePayLogPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iphone_pay_log
     *
     * @mbggenerated Thu Dec 01 11:45:12 CST 2016
     */
    int updateByExample(@Param("record") IphonePayLogPo record, @Param("example") IphonePayLogPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iphone_pay_log
     *
     * @mbggenerated Thu Dec 01 11:45:12 CST 2016
     */
    int updateByPrimaryKeySelective(IphonePayLogPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iphone_pay_log
     *
     * @mbggenerated Thu Dec 01 11:45:12 CST 2016
     */
    int updateByPrimaryKey(IphonePayLogPo record);
}