package com.ellis.pay.dal.db;

public class MerAcctInfoPoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mer_acct_info.mer_id
     *
     * @mbggenerated Thu Dec 01 10:59:02 CST 2016
     */
    private String merId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mer_acct_info.acct_id
     *
     * @mbggenerated Thu Dec 01 10:59:02 CST 2016
     */
    private String acctId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mer_acct_info.pay_channel
     *
     * @mbggenerated Thu Dec 01 10:59:02 CST 2016
     */
    private Byte payChannel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mer_acct_info.mer_id
     *
     * @return the value of mer_acct_info.mer_id
     *
     * @mbggenerated Thu Dec 01 10:59:02 CST 2016
     */
    public String getMerId() {
        return merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mer_acct_info.mer_id
     *
     * @param merId the value for mer_acct_info.mer_id
     *
     * @mbggenerated Thu Dec 01 10:59:02 CST 2016
     */
    public void setMerId(String merId) {
        this.merId = merId == null ? null : merId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mer_acct_info.acct_id
     *
     * @return the value of mer_acct_info.acct_id
     *
     * @mbggenerated Thu Dec 01 10:59:02 CST 2016
     */
    public String getAcctId() {
        return acctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mer_acct_info.acct_id
     *
     * @param acctId the value for mer_acct_info.acct_id
     *
     * @mbggenerated Thu Dec 01 10:59:02 CST 2016
     */
    public void setAcctId(String acctId) {
        this.acctId = acctId == null ? null : acctId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mer_acct_info.pay_channel
     *
     * @return the value of mer_acct_info.pay_channel
     *
     * @mbggenerated Thu Dec 01 10:59:02 CST 2016
     */
    public Byte getPayChannel() {
        return payChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mer_acct_info.pay_channel
     *
     * @param payChannel the value for mer_acct_info.pay_channel
     *
     * @mbggenerated Thu Dec 01 10:59:02 CST 2016
     */
    public void setPayChannel(Byte payChannel) {
        this.payChannel = payChannel;
    }
}