package com.ellis.pay.dal.db;

import com.ellis.pay.dal.db.MerAcctInfoPo;
import com.ellis.pay.dal.db.MerAcctInfoPoExample;
import com.ellis.pay.dal.db.MerAcctInfoPoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MerAcctInfoPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mer_acct_info
     *
     * @mbggenerated Thu Dec 01 10:59:02 CST 2016
     */
    int countByExample(MerAcctInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mer_acct_info
     *
     * @mbggenerated Thu Dec 01 10:59:02 CST 2016
     */
    int deleteByExample(MerAcctInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mer_acct_info
     *
     * @mbggenerated Thu Dec 01 10:59:02 CST 2016
     */
    int deleteByPrimaryKey(MerAcctInfoPoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mer_acct_info
     *
     * @mbggenerated Thu Dec 01 10:59:02 CST 2016
     */
    int insert(MerAcctInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mer_acct_info
     *
     * @mbggenerated Thu Dec 01 10:59:02 CST 2016
     */
    int insertSelective(MerAcctInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mer_acct_info
     *
     * @mbggenerated Thu Dec 01 10:59:02 CST 2016
     */
    List<MerAcctInfoPo> selectByExample(MerAcctInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mer_acct_info
     *
     * @mbggenerated Thu Dec 01 10:59:02 CST 2016
     */
    MerAcctInfoPo selectByPrimaryKey(MerAcctInfoPoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mer_acct_info
     *
     * @mbggenerated Thu Dec 01 10:59:02 CST 2016
     */
    int updateByExampleSelective(@Param("record") MerAcctInfoPo record, @Param("example") MerAcctInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mer_acct_info
     *
     * @mbggenerated Thu Dec 01 10:59:02 CST 2016
     */
    int updateByExample(@Param("record") MerAcctInfoPo record, @Param("example") MerAcctInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mer_acct_info
     *
     * @mbggenerated Thu Dec 01 10:59:02 CST 2016
     */
    int updateByPrimaryKeySelective(MerAcctInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mer_acct_info
     *
     * @mbggenerated Thu Dec 01 10:59:02 CST 2016
     */
    int updateByPrimaryKey(MerAcctInfoPo record);
}