package com.ellis.pay.dal.db;

import com.ellis.pay.dal.db.PayLogInfoPo;
import com.ellis.pay.dal.db.PayLogInfoPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PayLogInfoPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_log
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    int countByExample(PayLogInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_log
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    int deleteByExample(PayLogInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_log
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_log
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    int insert(PayLogInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_log
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    int insertSelective(PayLogInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_log
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    List<PayLogInfoPo> selectByExample(PayLogInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_log
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    PayLogInfoPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_log
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    int updateByExampleSelective(@Param("record") PayLogInfoPo record, @Param("example") PayLogInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_log
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    int updateByExample(@Param("record") PayLogInfoPo record, @Param("example") PayLogInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_log
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    int updateByPrimaryKeySelective(PayLogInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_log
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    int updateByPrimaryKey(PayLogInfoPo record);
}