package com.ellis.pay.dal.db;

import java.util.Date;

public class PayLogInfoPo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_log.id
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_log.uid
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_log.order_no
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_log.pay_acct
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    private String payAcct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_log.trade_no
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    private String tradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_log.pay_time
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_log.pay_amount
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    private Long payAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_log.pay_channel
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    private Byte payChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_log.pay_status
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    private Byte payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_log.last_notify_time
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    private Date lastNotifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_log.remark
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_log.id
     *
     * @return the value of pay_log.id
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_log.id
     *
     * @param id the value for pay_log.id
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_log.uid
     *
     * @return the value of pay_log.uid
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_log.uid
     *
     * @param uid the value for pay_log.uid
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_log.order_no
     *
     * @return the value of pay_log.order_no
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_log.order_no
     *
     * @param orderNo the value for pay_log.order_no
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_log.pay_acct
     *
     * @return the value of pay_log.pay_acct
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    public String getPayAcct() {
        return payAcct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_log.pay_acct
     *
     * @param payAcct the value for pay_log.pay_acct
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    public void setPayAcct(String payAcct) {
        this.payAcct = payAcct == null ? null : payAcct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_log.trade_no
     *
     * @return the value of pay_log.trade_no
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_log.trade_no
     *
     * @param tradeNo the value for pay_log.trade_no
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_log.pay_time
     *
     * @return the value of pay_log.pay_time
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_log.pay_time
     *
     * @param payTime the value for pay_log.pay_time
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_log.pay_amount
     *
     * @return the value of pay_log.pay_amount
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    public Long getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_log.pay_amount
     *
     * @param payAmount the value for pay_log.pay_amount
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    public void setPayAmount(Long payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_log.pay_channel
     *
     * @return the value of pay_log.pay_channel
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    public Byte getPayChannel() {
        return payChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_log.pay_channel
     *
     * @param payChannel the value for pay_log.pay_channel
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    public void setPayChannel(Byte payChannel) {
        this.payChannel = payChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_log.pay_status
     *
     * @return the value of pay_log.pay_status
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    public Byte getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_log.pay_status
     *
     * @param payStatus the value for pay_log.pay_status
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    public void setPayStatus(Byte payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_log.last_notify_time
     *
     * @return the value of pay_log.last_notify_time
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    public Date getLastNotifyTime() {
        return lastNotifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_log.last_notify_time
     *
     * @param lastNotifyTime the value for pay_log.last_notify_time
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    public void setLastNotifyTime(Date lastNotifyTime) {
        this.lastNotifyTime = lastNotifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_log.remark
     *
     * @return the value of pay_log.remark
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_log.remark
     *
     * @param remark the value for pay_log.remark
     *
     * @mbggenerated Thu Dec 01 00:20:12 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}